[package]
name = "mac-connect-client"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.28", default-features = true }
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading"
] }
image = { version = "0.25", default-features = false }
byteorder = "1.5"
crossbeam-channel = "0.5"
parking_lot = "0.12"
nokhwa = { version = "0.10", default-features = false, features = ["input-native", "output-threaded"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
